/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// ⚠️ INSTRUCCIONES: Actualiza estos valores con tu proyecto de Supabase
// 1. Ve a: https://supabase.com/dashboard
// 2. Abre tu proyecto (o crea uno nuevo)
// 3. Ve a Settings → API
// 4. Copia "Project URL" y extrae el ID (la parte entre https:// y .supabase.co)
//    Ejemplo: si tu URL es "https://abcdefgh12345678.supabase.co"
//    entonces tu projectId es: "abcdefgh12345678"
// 5. Copia "anon public" key (la key que empieza con "eyJ...")

// 🔧 CREDENCIALES DE SUPABASE CONFIGURADAS:
export const projectId = "cqpeyzmygcraupjjomfg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxcGV5em15Z2NyYXVwampvbWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2ODQ1ODUsImV4cCI6MjA3ODI2MDU4NX0.EjByo5rR50IVYHeJrfgSb7brPxGbtyBtW0XZqY7j7wk"

// ✅ Tu proyecto está conectado a: https://cqpeyzmygcraupjjomfg.supabase.co
