import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en' | 'it' | 'de' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentLanguage: Language;
  changeLanguage: (lang: Language) => void;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navegación y menú
    'dashboard': 'Panel',
    'assignments': 'Tareas',
    'grades': 'Calificaciones',
    'students': 'Estudiantes',
    'submissions': 'Mis Entregas',
    'logout': 'Cerrar Sesión',
    'myStudents': 'Mis Estudiantes',
    'allStudents': 'Todos los Estudiantes',
    
    // Autenticación
    'login': 'Iniciar Sesión',
    'signup': 'Registrarse',
    'email': 'Correo electrónico',
    'password': 'Contraseña',
    'name': 'Nombre',
    'fullName': 'Nombre completo',
    'role': 'Rol',
    'teacher': 'Profesor',
    'student': 'Estudiante',
    'alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'dontHaveAccount': '¿No tienes cuenta? Usa la pestaña "Registrarse"',
    'signingIn': 'Iniciando sesión...',
    'registering': 'Registrando...',
    'createAccount': 'Crear Cuenta',
    'iAm': 'Soy un...',
    'modernEducationalPlatform': 'Plataforma educativa moderna',
    'invalidCredentials': 'Credenciales inválidas. Por favor verifica tu email y contraseña, o crea una cuenta nueva en "Registrarse".',
    'loginError': 'Error al iniciar sesión',
    'signupError': 'Error al registrarse',
    'adminLoginHint': 'Para admin use: admin / EduConnect@Admin2024',
    
    // Dashboard
    'welcome': 'Bienvenido',
    'teacherPanel': 'Panel del Profesor',
    'studentPanel': 'Panel del Estudiante',
    'totalAssignments': 'Total de Tareas',
    'totalStudents': 'Total de Estudiantes',
    'myStudentsCount': 'Mis Estudiantes',
    'activeAssignments': 'Tareas Activas',
    'pendingSubmissions': 'Entregas Pendientes',
    'recentAssignments': 'Tareas Recientes',
    'upcomingAssignments': 'Próximas Tareas',
    'completedAssignments': 'Tareas Completadas',
    'averageGrade': 'Promedio',
    'myTasks': 'Mis Tareas',
    'manageTasks': 'Administra tus tareas y actividades',
    'loadingTasks': 'Cargando tareas...',
    'loadingSubmissions': 'Cargando entregas...',
    'noAssignments': 'No hay tareas creadas',
    'noAssignmentsMessage': 'Comienza creando tu primera tarea para tus estudiantes',
    'createFirstTask': 'Crear Primera Tarea',
    'noAssignedTasks': 'No tienes tareas asignadas',
    'noAssignedTasksMessage': 'Tu profesor aún no te ha asignado ninguna tarea.',
    'noSubmissions': 'No tienes entregas',
    'noSubmissionsMessage': 'Aún no has entregado ninguna tarea.',
    
    // Tareas
    'createAssignment': 'Crear Nueva Tarea',
    'newTask': 'Nueva Tarea',
    'assignmentTitle': 'Título de la Tarea',
    'description': 'Descripción',
    'dueDate': 'Fecha de Entrega',
    'submit': 'Entregar',
    'submitted': 'Entregado',
    'pending': 'Pendiente',
    'graded': 'Calificado',
    'notGraded': 'Sin Calificar',
    'viewDetails': 'Ver Detalles',
    'delete': 'Eliminar',
    'assignmentDetails': 'Detalles de la Tarea',
    'submissionDetails': 'Detalles de la Entrega',
    'yourAnswer': 'Tu respuesta',
    'submitAssignment': 'Entregar Tarea',
    'confirmDelete': '¿Estás seguro de que quieres eliminar esta tarea?',
    'deleteError': 'Error al eliminar la tarea',
    'createError': 'Error al crear la tarea',
    'grade': 'Calificación',
    'feedback': 'Retroalimentación',
    'saveGrade': 'Guardar Calificación',
    'gradeStudent': 'Calificar Estudiante',
    'enterGrade': 'Ingresa una calificación (0-100)',
    'enterFeedback': 'Escribe tu retroalimentación...',
    
    // Tipos de actividades
    'standard': 'Estándar',
    'interactive': 'Interactivo',
    'form': 'Formulario',
    'video': 'Video',
    
    // Actividades interactivas
    'fillBlanks': 'Rellenar Espacios',
    'matchPairs': 'Conectar Parejas',
    'sequence': 'Ordenar',
    'categorize': 'Categorizar',
    'trueFalse': 'Verdadero/Falso',
    'imageChoice': 'Elección Visual',
    'addActivity': 'Agregar Actividad',
    'activityType': 'Tipo de Actividad',
    'question': 'Pregunta',
    'correctAnswer': 'Respuesta Correcta',
    'addOption': 'Agregar Opción',
    'option': 'Opción',
    'true': 'Verdadero',
    'false': 'Falso',
    'category': 'Categoría',
    'addCategory': 'Agregar Categoría',
    'addItem': 'Agregar Elemento',
    'item': 'Elemento',
    'pair': 'Pareja',
    'addPair': 'Agregar Pareja',
    
    // Formularios
    'addField': 'Agregar Campo',
    'fieldLabel': 'Etiqueta del Campo',
    'fieldType': 'Tipo de Campo',
    'required': 'Obligatorio',
    'text': 'Texto',
    'textarea': 'Área de Texto',
    'number': 'Número',
    'date': 'Fecha',
    'checkbox': 'Casilla',
    'select': 'Selección',
    'radio': 'Opción Múltiple',
    'options': 'Opciones (separadas por comas)',
    
    // Archivos y multimedia
    'attachedFiles': 'Archivos Adjuntos (PDFs, documentos, etc.)',
    'clickToUpload': 'Click para subir archivos',
    'uploading': 'Subiendo...',
    'uploadError': 'Error al subir archivos',
    'videoUrl': 'URL del Video',
    'videoSupport': 'Soporta YouTube, Vimeo y enlaces directos a archivos de video',
    'uploadVideo': 'O sube un video desde tu computadora',
    'clickToUploadVideo': 'Click para subir video',
    
    // Estudiantes y asignaciones
    'assignStudents': 'Asignar Estudiantes',
    'assignedStudents': 'Estudiantes Asignados',
    'availableStudents': 'Estudiantes Disponibles',
    'assign': 'Asignar',
    'unassign': 'Desasignar',
    'assignToMe': 'Asignar a Mí',
    'unassignFromMe': 'Desasignar de Mí',
    'myTeacher': 'Mi Profesor',
    'noTeacher': 'Sin profesor asignado',
    'assignSuccess': 'Asignación exitosa',
    'assignError': 'Error al asignar',
    'assignStudentSuccess': 'Estudiante asignado correctamente',
    'unassignStudentSuccess': 'Estudiante desasignado correctamente',
    'assignTaskSuccess': 'Tarea asignada correctamente',
    'unassignTaskSuccess': 'Tarea desasignada correctamente',
    'studentsAssigned': 'estudiantes asignados',
    'submissions': 'entregas',
    'howAssignmentWorks': '💡 ¿Cómo funciona el sistema de asignaciones?',
    'assignmentStep1': 'Crea una tarea usando el botón "Nueva Tarea"',
    'assignmentStep2': 'Ve a "Todos los Estudiantes" y asigna estudiantes a ti',
    'assignmentStep3': 'Desde cada tarea, usa el botón de usuarios para asignarla a estudiantes específicos',
    'assignmentStep4': 'Los estudiantes solo verán las tareas que les hayas asignado',
    
    // Calificaciones
    'viewGrades': 'Ver Calificaciones',
    'studentGrades': 'Calificaciones de Estudiantes',
    'assignmentGrades': 'Calificaciones por Tarea',
    'noGrades': 'No hay calificaciones disponibles',
    'noGradesMessage': 'Aún no hay entregas calificadas.',
    'points': 'puntos',
    
    // General
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'edit': 'Editar',
    'close': 'Cerrar',
    'loading': 'Cargando...',
    'noData': 'No hay datos disponibles',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'settings': 'Configuración',
    'settingsDescription': 'Personaliza tu perfil, tema y preferencias de idioma',
    'profile': 'Perfil',
    'language': 'Idioma',
    'theme': 'Tema',
    'lightMode': 'Modo Claro',
    'darkMode': 'Modo Oscuro',
    'selectLanguage': 'Seleccionar Idioma',
    'changeAvatar': 'Cambiar Avatar',
    'selectAvatar': 'Selecciona tu Avatar',
    'skinTone': 'Tono de Piel',
    'hairColor': 'Color de Cabello',
    'style': 'Estilo',
    'customization': 'Personalización',
    'appearance': 'Apariencia',
    'saveChanges': 'Guardar Cambios',
    'changesSaved': 'Cambios guardados correctamente',
    'errorSavingChanges': 'Error al guardar los cambios',
    'unsavedChanges': '¿Descartar cambios no guardados?',
    'saving': 'Guardando...',
    'uploadOwn': 'Subir propia',
    'uploadRequirements': 'Requisitos de subida',
    'maxFileSize': 'Peso máximo: 2 MB',
    'maxDimensions': 'Dimensiones máximas: 2000 x 2000 px',
    'allowedFormats': 'Formatos permitidos: PNG, JPG, JPEG',
    'invalidFileType': 'Solo se permiten archivos PNG o JPG/JPEG',
    'fileTooLarge': 'Archivo muy grande',
    'imageTooLarge': 'Imagen muy grande',
    'invalidImage': 'Imagen inválida',
    'imageValidated': '✓ Imagen validada correctamente',
    'upTo': 'hasta',
    'select': 'Seleccionar',
    
    // Mensajes de error y estado
    'error': 'Error',
    'success': 'Éxito',
    'warning': 'Advertencia',
    'info': 'Información',
    
    // Placeholders
    'enterTitle': 'Ej: Ensayo sobre la Revolución Industrial',
    'enterDescription': 'Describe los objetivos y requisitos de la tarea...',
    'enterEmail': 'tu@email.com',
    'enterName': 'Juan Pérez',
    
    // Diálogos y confirmaciones
    'createTaskDialog': 'Crea una tarea, formulario interactivo o sube contenido multimedia',
    'pleaseEnterTitle': 'Por favor ingresa un título',
    
    // Tabs y navegación
    'tasks': 'Tareas',
    'mySubmissions': 'Mis Entregas',
    'allSubmissions': 'Todas las Entregas',
    
    // Admin Panel
    'totalUsers': 'Total de Usuarios',
    'teachers': 'Profesores',
    'userManagement': 'Gestión de Usuarios',
    'manageUsersDescription': 'Ver, gestionar y moderar todos los usuarios del sistema',
    'allUsers': 'Todos los Usuarios',
    'noUsers': 'No se encontraron usuarios',
    'noTeachers': 'No se encontraron profesores',
    'noStudents': 'No se encontraron estudiantes',
    'confirmDeleteUser': '¿Estás seguro de que quieres eliminar a',
    'userDeleted': 'Usuario eliminado exitosamente',
    'errorDeletingUser': 'Error al eliminar usuario',
    'errorLoadingUsers': 'Error al cargar usuarios',
    'noUsersWarning': '⚠️ No se pueden cargar usuarios',
    'serverDeploymentIssue': 'El servidor Edge Function no está desplegado (Error 403). Por favor, revisa el archivo ERROR_403_QUICK_FIX.md para solucionar este problema de infraestructura.',
    'codeCorrectNote': 'Nota: El código está correcto. Solo necesitas configurar Supabase correctamente.',
    'userBlocked': 'bloqueado',
    'userUnblocked': 'desbloqueado',
    'errorUpdatingUser': 'Error al actualizar usuario',
    'blocked': 'Bloqueado',
    'block': 'Bloquear',
    'unblock': 'Desbloquear',
    'assignTeacher': 'Asignar Profesor',
    'assignTeacherTo': 'Asignar Profesor a',
    'selectTeacherDescription': 'Selecciona un profesor para asignar a este estudiante',
    'selectTeacher': 'Selecciona un profesor',
    'teacherAssigned': 'Profesor asignado exitosamente',
    'errorAssigningTeacher': 'Error al asignar profesor',
    'saving': 'Guardando...',
    'of': 'de',
    'selectAll': 'Seleccionar Todos',
    
    // NOTAS / Material Complementario
    'notes': 'Material',
    'materials': 'Material Complementario',
    'notesDescription': 'Material de apoyo y recursos educativos',
    'createNote': 'Subir Material',
    'newMaterial': 'Nuevo Material',
    'noteTitle': 'Título del Material',
    'noteType': 'Tipo de Material',
    'book': 'Libro',
    'pdf': 'PDF',
    'photo': 'Foto/Imagen',
    'audio': 'Audio',
    'noNotes': 'No hay materiales',
    'noNotesMessage': 'Sube tu primer material educativo para tus estudiantes',
    'uploadMaterial': 'Subir Material',
    'assignNotes': 'Asignar Material',
    'statusNew': 'Nuevo',
    'statusUnread': 'Sin Leer',
    'statusRead': 'Leído',
    'markAsRead': 'Marcar como Leído',
    'deleteNote': 'Eliminar Material',
    'confirmDeleteNote': '¿Estás seguro de que quieres eliminar este material?',
    'noteDeleted': 'Material eliminado correctamente',
    'noteCreated': 'Material creado correctamente',
    'noteAssigned': 'Material asignado correctamente',
    'materialsAssigned': 'materiales asignados',
    'totalMaterials': 'Total de Materiales',
    'myMaterials': 'Mi Material',
    
    // Creación de tareas con IA
    'createWithAI': 'Crear con IA',
    'aiTaskCreation': 'Creación de Tarea con IA',
    'uploadContent': 'Subir Contenido',
    'contentType': 'Tipo de Contenido',
    'pasteText': 'Pegar Texto',
    'uploadImage': 'Subir Imagen',
    'videoLink': 'Enlace de Video',
    'uploadPDF': 'Subir PDF',
    'generateTask': 'Generar Tarea',
    'aiGenerating': 'IA generando tarea...',
    'editGeneratedTask': 'Editar Tarea Generada',
    'generatePDFAndAssign': 'Generar PDF y Asignar',
    'aiAnalyzing': 'IA analizando contenido...',
    'aiError': 'Error al generar con IA',
    
    // Organización temporal
    'year': 'Año',
    'month': 'Mes',
    'week': 'Semana',
    'january': 'Enero',
    'february': 'Febrero',
    'march': 'Marzo',
    'april': 'Abril',
    'may': 'Mayo',
    'june': 'Junio',
    'july': 'Julio',
    'august': 'Agosto',
    'september': 'Septiembre',
    'october': 'Octubre',
    'november': 'Noviembre',
    'december': 'Diciembre',
    'weekOf': 'Semana del',
    'to': 'al',
    
    // Tareas resueltas
    'completed': 'Completada',
    'viewSubmission': 'Ver Entrega',
    'reassigned': 'Reasignada',
    'attemptHistory': 'Historial de Intentos',
    'attempt': 'Intento',
    'previousAttempts': 'Intentos Anteriores',
    
    // Estado del servidor
    'checkingServer': 'Verificando Servidor',
    'serverOffline': 'Servidor Fuera de Línea',
    'serverOnline': 'Servidor Conectado',
    'checkingServerMessage': 'Verificando conexión con el servidor...',
    'serverOfflineMessage': 'No se puede conectar al servidor. Algunas funcionalidades pueden no estar disponibles.',
    'serverOfflineReason1': '• El servidor Edge Function no está desplegado (Error 403)',
    'serverOfflineReason2': '• Verifica el estado del deployment en Supabase Dashboard',
    'moreInfo': 'Más información',
  },
  
  en: {
    // Navigation and menu
    'dashboard': 'Dashboard',
    'assignments': 'Assignments',
    'grades': 'Grades',
    'students': 'Students',
    'submissions': 'My Submissions',
    'logout': 'Logout',
    'myStudents': 'My Students',
    'allStudents': 'All Students',
    
    // Authentication
    'login': 'Login',
    'signup': 'Sign Up',
    'email': 'Email',
    'password': 'Password',
    'name': 'Name',
    'fullName': 'Full Name',
    'role': 'Role',
    'teacher': 'Teacher',
    'student': 'Student',
    'alreadyHaveAccount': 'Already have an account?',
    'dontHaveAccount': "Don't have an account? Use the \"Sign Up\" tab",
    'signingIn': 'Signing in...',
    'registering': 'Registering...',
    'createAccount': 'Create Account',
    'iAm': 'I am a...',
    'modernEducationalPlatform': 'Modern educational platform',
    'invalidCredentials': 'Invalid credentials. Please verify your email and password, or create a new account in "Sign Up".',
    'loginError': 'Login error',
    'signupError': 'Sign up error',
    
    // Dashboard
    'welcome': 'Welcome',
    'teacherPanel': 'Teacher Panel',
    'studentPanel': 'Student Panel',
    'totalAssignments': 'Total Assignments',
    'totalStudents': 'Total Students',
    'myStudentsCount': 'My Students',
    'activeAssignments': 'Active Assignments',
    'pendingSubmissions': 'Pending Submissions',
    'recentAssignments': 'Recent Assignments',
    'upcomingAssignments': 'Upcoming Assignments',
    'completedAssignments': 'Completed Assignments',
    'averageGrade': 'Average',
    'myTasks': 'My Tasks',
    'manageTasks': 'Manage your tasks and activities',
    'loadingTasks': 'Loading tasks...',
    'loadingSubmissions': 'Loading submissions...',
    'noAssignments': 'No assignments created',
    'noAssignmentsMessage': 'Start by creating your first assignment for your students',
    'createFirstTask': 'Create First Task',
    'noAssignedTasks': 'No assignments assigned',
    'noAssignedTasksMessage': 'Your teacher has not assigned you any tasks yet.',
    'noSubmissions': 'No submissions',
    'noSubmissionsMessage': "You haven't submitted any assignments yet.",
    
    // Assignments
    'createAssignment': 'Create New Assignment',
    'newTask': 'New Task',
    'assignmentTitle': 'Assignment Title',
    'description': 'Description',
    'dueDate': 'Due Date',
    'submit': 'Submit',
    'submitted': 'Submitted',
    'pending': 'Pending',
    'graded': 'Graded',
    'notGraded': 'Not Graded',
    'viewDetails': 'View Details',
    'delete': 'Delete',
    'assignmentDetails': 'Assignment Details',
    'submissionDetails': 'Submission Details',
    'yourAnswer': 'Your answer',
    'submitAssignment': 'Submit Assignment',
    'confirmDelete': 'Are you sure you want to delete this assignment?',
    'deleteError': 'Error deleting assignment',
    'createError': 'Error creating assignment',
    'grade': 'Grade',
    'feedback': 'Feedback',
    'saveGrade': 'Save Grade',
    'gradeStudent': 'Grade Student',
    'enterGrade': 'Enter a grade (0-100)',
    'enterFeedback': 'Write your feedback...',
    
    // Activity types
    'standard': 'Standard',
    'interactive': 'Interactive',
    'form': 'Form',
    'video': 'Video',
    
    // Interactive activities
    'fillBlanks': 'Fill in the Blanks',
    'matchPairs': 'Match Pairs',
    'sequence': 'Sequence',
    'categorize': 'Categorize',
    'trueFalse': 'True/False',
    'imageChoice': 'Image Choice',
    'addActivity': 'Add Activity',
    'activityType': 'Activity Type',
    'question': 'Question',
    'correctAnswer': 'Correct Answer',
    'addOption': 'Add Option',
    'option': 'Option',
    'true': 'True',
    'false': 'False',
    'category': 'Category',
    'addCategory': 'Add Category',
    'addItem': 'Add Item',
    'item': 'Item',
    'pair': 'Pair',
    'addPair': 'Add Pair',
    
    // Forms
    'addField': 'Add Field',
    'fieldLabel': 'Field Label',
    'fieldType': 'Field Type',
    'required': 'Required',
    'text': 'Text',
    'textarea': 'Text Area',
    'number': 'Number',
    'date': 'Date',
    'checkbox': 'Checkbox',
    'select': 'Select',
    'radio': 'Radio',
    'options': 'Options (comma separated)',
    
    // Files and media
    'attachedFiles': 'Attached Files (PDFs, documents, etc.)',
    'clickToUpload': 'Click to upload files',
    'uploading': 'Uploading...',
    'uploadError': 'Error uploading files',
    'videoUrl': 'Video URL',
    'videoSupport': 'Supports YouTube, Vimeo and direct video file links',
    'uploadVideo': 'Or upload a video from your computer',
    'clickToUploadVideo': 'Click to upload video',
    
    // Students and assignments
    'assignStudents': 'Assign Students',
    'assignedStudents': 'Assigned Students',
    'availableStudents': 'Available Students',
    'assign': 'Assign',
    'unassign': 'Unassign',
    'assignToMe': 'Assign to Me',
    'unassignFromMe': 'Unassign from Me',
    'myTeacher': 'My Teacher',
    'noTeacher': 'No teacher assigned',
    'assignSuccess': 'Successfully assigned',
    'assignError': 'Assignment error',
    'assignStudentSuccess': 'Student assigned successfully',
    'unassignStudentSuccess': 'Student unassigned successfully',
    'assignTaskSuccess': 'Task assigned successfully',
    'unassignTaskSuccess': 'Task unassigned successfully',
    'studentsAssigned': 'students assigned',
    'submissions': 'submissions',
    'howAssignmentWorks': '💡 How does the assignment system work?',
    'assignmentStep1': 'Create a task using the "New Task" button',
    'assignmentStep2': 'Go to "All Students" and assign students to yourself',
    'assignmentStep3': 'From each task, use the users button to assign it to specific students',
    'assignmentStep4': 'Students will only see tasks that you have assigned to them',
    
    // Grades
    'viewGrades': 'View Grades',
    'studentGrades': 'Student Grades',
    'assignmentGrades': 'Grades by Assignment',
    'noGrades': 'No grades available',
    'noGradesMessage': 'There are no graded submissions yet.',
    'points': 'points',
    
    // General
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'close': 'Close',
    'loading': 'Loading...',
    'noData': 'No data available',
    'search': 'Search',
    'filter': 'Filter',
    'settings': 'Settings',
    'settingsDescription': 'Customize your profile, theme, and language preferences',
    'profile': 'Profile',
    'language': 'Language',
    'theme': 'Theme',
    'lightMode': 'Light Mode',
    'darkMode': 'Dark Mode',
    'selectLanguage': 'Select Language',
    'changeAvatar': 'Change Avatar',
    'selectAvatar': 'Select Your Avatar',
    'skinTone': 'Skin Tone',
    'hairColor': 'Hair Color',
    'style': 'Style',
    'customization': 'Customization',
    'appearance': 'Appearance',
    'saveChanges': 'Save Changes',
    'changesSaved': 'Changes saved successfully',
    'errorSavingChanges': 'Error saving changes',
    'unsavedChanges': 'Discard unsaved changes?',
    'saving': 'Saving...',
    'uploadOwn': 'Upload own',
    'uploadRequirements': 'Upload requirements',
    'maxFileSize': 'Max file size: 2 MB',
    'maxDimensions': 'Max dimensions: 2000 x 2000 px',
    'allowedFormats': 'Allowed formats: PNG, JPG, JPEG',
    'invalidFileType': 'Only PNG or JPG/JPEG files allowed',
    'fileTooLarge': 'File too large',
    'imageTooLarge': 'Image too large',
    'invalidImage': 'Invalid image',
    'imageValidated': '✓ Image validated successfully',
    'upTo': 'up to',
    'select': 'Select',
    
    // Error and status messages
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Information',
    
    // Placeholders
    'enterTitle': 'E.g: Essay on the Industrial Revolution',
    'enterDescription': 'Describe the objectives and requirements of the task...',
    'enterEmail': 'you@email.com',
    'enterName': 'John Doe',
    
    // Dialogs and confirmations
    'createTaskDialog': 'Create a task, interactive form or upload multimedia content',
    'pleaseEnterTitle': 'Please enter a title',
    
    // Tabs and navigation
    'tasks': 'Tasks',
    'mySubmissions': 'My Submissions',
    'allSubmissions': 'All Submissions',
    
    // Admin Panel
    'totalUsers': 'Total Users',
    'teachers': 'Teachers',
    'userManagement': 'User Management',
    'manageUsersDescription': 'View, manage, and moderate all users in the system',
    'allUsers': 'All Users',
    'noUsers': 'No users found',
    'noTeachers': 'No teachers found',
    'noStudents': 'No students found',
    'confirmDeleteUser': 'Are you sure you want to delete',
    'userDeleted': 'User deleted successfully',
    'errorDeletingUser': 'Error deleting user',
    'errorLoadingUsers': 'Error loading users',
    'noUsersWarning': '⚠️ Cannot load users',
    'serverDeploymentIssue': 'The Edge Function server is not deployed (Error 403). Please check the ERROR_403_QUICK_FIX.md file to solve this infrastructure issue.',
    'codeCorrectNote': 'Note: The code is correct. You just need to configure Supabase correctly.',
    'userBlocked': 'blocked',
    'userUnblocked': 'unblocked',
    'errorUpdatingUser': 'Error updating user',
    'blocked': 'Blocked',
    'block': 'Block',
    'unblock': 'Unblock',
    'assignTeacher': 'Assign Teacher',
    'assignTeacherTo': 'Assign Teacher to',
    'selectTeacherDescription': 'Select a teacher to assign to this student',
    'selectTeacher': 'Select a teacher',
    'teacherAssigned': 'Teacher assigned successfully',
    'errorAssigningTeacher': 'Error assigning teacher',
    'adminLoginHint': 'For admin use: admin / EduConnect@Admin2024',
    'saving': 'Saving...',
    'of': 'of',
    'selectAll': 'Select All',
    
    // NOTES / Supplementary Material
    'notes': 'Materials',
    'materials': 'Supplementary Materials',
    'notesDescription': 'Support materials and educational resources',
    'createNote': 'Upload Material',
    'newMaterial': 'New Material',
    'noteTitle': 'Material Title',
    'noteType': 'Material Type',
    'book': 'Book',
    'pdf': 'PDF',
    'photo': 'Photo/Image',
    'audio': 'Audio',
    'noNotes': 'No materials',
    'noNotesMessage': 'Upload your first educational material for your students',
    'uploadMaterial': 'Upload Material',
    'assignNotes': 'Assign Material',
    'statusNew': 'New',
    'statusUnread': 'Unread',
    'statusRead': 'Read',
    'markAsRead': 'Mark as Read',
    'deleteNote': 'Delete Material',
    'confirmDeleteNote': 'Are you sure you want to delete this material?',
    'noteDeleted': 'Material deleted successfully',
    'noteCreated': 'Material created successfully',
    'noteAssigned': 'Material assigned successfully',
    'materialsAssigned': 'materials assigned',
    'totalMaterials': 'Total Materials',
    'myMaterials': 'My Materials',
    
    // AI Task Creation
    'createWithAI': 'Create with AI',
    'aiTaskCreation': 'AI Task Creation',
    'uploadContent': 'Upload Content',
    'contentType': 'Content Type',
    'pasteText': 'Paste Text',
    'uploadImage': 'Upload Image',
    'videoLink': 'Video Link',
    'uploadPDF': 'Upload PDF',
    'generateTask': 'Generate Task',
    'aiGenerating': 'AI generating task...',
    'editGeneratedTask': 'Edit Generated Task',
    'generatePDFAndAssign': 'Generate PDF and Assign',
    'aiAnalyzing': 'AI analyzing content...',
    'aiError': 'Error generating with AI',
    
    // Time Organization
    'year': 'Year',
    'month': 'Month',
    'week': 'Week',
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    'weekOf': 'Week of',
    'to': 'to',
    
    // Completed Tasks
    'completed': 'Completed',
    'viewSubmission': 'View Submission',
    'reassigned': 'Reassigned',
    'attemptHistory': 'Attempt History',
    'attempt': 'Attempt',
    'previousAttempts': 'Previous Attempts',
  },
  
  it: {
    // Navigazione e menu
    'dashboard': 'Pannello',
    'assignments': 'Compiti',
    'grades': 'Voti',
    'students': 'Studenti',
    'submissions': 'Le Mie Consegne',
    'logout': 'Esci',
    'myStudents': 'I Miei Studenti',
    'allStudents': 'Tutti gli Studenti',
    
    // Autenticazione
    'login': 'Accedi',
    'signup': 'Registrati',
    'email': 'Email',
    'password': 'Password',
    'name': 'Nome',
    'fullName': 'Nome Completo',
    'role': 'Ruolo',
    'teacher': 'Insegnante',
    'student': 'Studente',
    'alreadyHaveAccount': 'Hai già un account?',
    'dontHaveAccount': 'Non hai un account? Usa la scheda "Registrati"',
    'signingIn': 'Accesso in corso...',
    'registering': 'Registrazione in corso...',
    'createAccount': 'Crea Account',
    'iAm': 'Sono un...',
    'modernEducationalPlatform': 'Piattaforma educativa moderna',
    'invalidCredentials': 'Credenziali non valide. Verifica la tua email e password, o crea un nuovo account in "Registrati".',
    'loginError': 'Errore di accesso',
    'signupError': 'Errore di registrazione',
    
    // Dashboard
    'welcome': 'Benvenuto',
    'teacherPanel': 'Pannello Insegnante',
    'studentPanel': 'Pannello Studente',
    'totalAssignments': 'Compiti Totali',
    'totalStudents': 'Studenti Totali',
    'myStudentsCount': 'I Miei Studenti',
    'activeAssignments': 'Compiti Attivi',
    'pendingSubmissions': 'Consegne in Sospeso',
    'recentAssignments': 'Compiti Recenti',
    'upcomingAssignments': 'Prossimi Compiti',
    'completedAssignments': 'Compiti Completati',
    'averageGrade': 'Media',
    'myTasks': 'I Miei Compiti',
    'manageTasks': 'Gestisci i tuoi compiti e attività',
    'loadingTasks': 'Caricamento compiti...',
    'loadingSubmissions': 'Caricamento consegne...',
    'noAssignments': 'Nessun compito creato',
    'noAssignmentsMessage': 'Inizia creando il tuo primo compito per i tuoi studenti',
    'createFirstTask': 'Crea Primo Compito',
    'noAssignedTasks': 'Nessun compito assegnato',
    'noAssignedTasksMessage': "Il tuo insegnante non ti ha ancora assegnato alcun compito.",
    'noSubmissions': 'Nessuna consegna',
    'noSubmissionsMessage': 'Non hai ancora consegnato alcun compito.',
    
    // Compiti
    'createAssignment': 'Crea Nuovo Compito',
    'newTask': 'Nuovo Compito',
    'assignmentTitle': 'Titolo del Compito',
    'description': 'Descrizione',
    'dueDate': 'Data di Consegna',
    'submit': 'Invia',
    'submitted': 'Consegnato',
    'pending': 'In Sospeso',
    'graded': 'Valutato',
    'notGraded': 'Non Valutato',
    'viewDetails': 'Vedi Dettagli',
    'delete': 'Elimina',
    'assignmentDetails': 'Dettagli del Compito',
    'submissionDetails': 'Dettagli della Consegna',
    'yourAnswer': 'La tua risposta',
    'submitAssignment': 'Invia Compito',
    'confirmDelete': 'Sei sicuro di voler eliminare questo compito?',
    'deleteError': 'Errore durante l\'eliminazione del compito',
    'createError': 'Errore durante la creazione del compito',
    'grade': 'Voto',
    'feedback': 'Feedback',
    'saveGrade': 'Salva Voto',
    'gradeStudent': 'Valuta Studente',
    'enterGrade': 'Inserisci un voto (0-100)',
    'enterFeedback': 'Scrivi il tuo feedback...',
    
    // Tipi di attività
    'standard': 'Standard',
    'interactive': 'Interattivo',
    'form': 'Modulo',
    'video': 'Video',
    
    // Attività interattive
    'fillBlanks': 'Riempi gli Spazi',
    'matchPairs': 'Abbina Coppie',
    'sequence': 'Sequenza',
    'categorize': 'Categorizza',
    'trueFalse': 'Vero/Falso',
    'imageChoice': 'Scelta Immagine',
    'addActivity': 'Aggiungi Attività',
    'activityType': 'Tipo di Attività',
    'question': 'Domanda',
    'correctAnswer': 'Risposta Corretta',
    'addOption': 'Aggiungi Opzione',
    'option': 'Opzione',
    'true': 'Vero',
    'false': 'Falso',
    'category': 'Categoria',
    'addCategory': 'Aggiungi Categoria',
    'addItem': 'Aggiungi Elemento',
    'item': 'Elemento',
    'pair': 'Coppia',
    'addPair': 'Aggiungi Coppia',
    
    // Moduli
    'addField': 'Aggiungi Campo',
    'fieldLabel': 'Etichetta Campo',
    'fieldType': 'Tipo di Campo',
    'required': 'Obbligatorio',
    'text': 'Testo',
    'textarea': 'Area Testo',
    'number': 'Numero',
    'date': 'Data',
    'checkbox': 'Casella di Controllo',
    'select': 'Seleziona',
    'radio': 'Radio',
    'options': 'Opzioni (separate da virgole)',
    
    // File e media
    'attachedFiles': 'File Allegati (PDF, documenti, ecc.)',
    'clickToUpload': 'Clicca per caricare file',
    'uploading': 'Caricamento...',
    'uploadError': 'Errore durante il caricamento dei file',
    'videoUrl': 'URL Video',
    'videoSupport': 'Supporta YouTube, Vimeo e link diretti a file video',
    'uploadVideo': 'Oppure carica un video dal tuo computer',
    'clickToUploadVideo': 'Clicca per caricare video',
    
    // Studenti e assegnazioni
    'assignStudents': 'Assegna Studenti',
    'assignedStudents': 'Studenti Assegnati',
    'availableStudents': 'Studenti Disponibili',
    'assign': 'Assegna',
    'unassign': 'Rimuovi',
    'assignToMe': 'Assegna a Me',
    'unassignFromMe': 'Rimuovi da Me',
    'myTeacher': 'Il Mio Insegnante',
    'noTeacher': 'Nessun insegnante assegnato',
    'assignSuccess': 'Assegnazione riuscita',
    'assignError': 'Errore di assegnazione',
    'assignStudentSuccess': 'Studente assegnato con successo',
    'unassignStudentSuccess': 'Studente rimosso con successo',
    'assignTaskSuccess': 'Compito assegnato con successo',
    'unassignTaskSuccess': 'Compito rimosso con successo',
    'studentsAssigned': 'studenti assegnati',
    'submissions': 'consegne',
    'howAssignmentWorks': '💡 Come funziona il sistema di assegnazione?',
    'assignmentStep1': 'Crea un compito usando il pulsante "Nuovo Compito"',
    'assignmentStep2': 'Vai su "Tutti gli Studenti" e assegna studenti a te stesso',
    'assignmentStep3': 'Da ogni compito, usa il pulsante utenti per assegnarlo a studenti specifici',
    'assignmentStep4': 'Gli studenti vedranno solo i compiti che hai assegnato loro',
    
    // Voti
    'viewGrades': 'Vedi Voti',
    'studentGrades': 'Voti degli Studenti',
    'assignmentGrades': 'Voti per Compito',
    'noGrades': 'Nessun voto disponibile',
    'noGradesMessage': 'Non ci sono ancora consegne valutate.',
    'points': 'punti',
    
    // Generale
    'save': 'Salva',
    'cancel': 'Annulla',
    'edit': 'Modifica',
    'close': 'Chiudi',
    'loading': 'Caricamento...',
    'noData': 'Nessun dato disponibile',
    'search': 'Cerca',
    'filter': 'Filtra',
    'settings': 'Impostazioni',
    'settingsDescription': 'Personalizza il tuo profilo, tema e preferenze di lingua',
    'profile': 'Profilo',
    'language': 'Lingua',
    'theme': 'Tema',
    'lightMode': 'Modalità Chiara',
    'darkMode': 'Modalità Scura',
    'selectLanguage': 'Seleziona Lingua',
    'changeAvatar': 'Cambia Avatar',
    'selectAvatar': 'Seleziona il Tuo Avatar',
    'skinTone': 'Tonalità Pelle',
    'hairColor': 'Colore Capelli',
    'style': 'Stile',
    'customization': 'Personalizzazione',
    'appearance': 'Aspetto',
    'saveChanges': 'Salva Modifiche',
    'changesSaved': 'Modifiche salvate con successo',
    'errorSavingChanges': 'Errore nel salvare le modifiche',
    'unsavedChanges': 'Scartare le modifiche non salvate?',
    'saving': 'Salvataggio...',
    'uploadOwn': 'Carica propria',
    'uploadRequirements': 'Requisiti di caricamento',
    'maxFileSize': 'Dimensione massima: 2 MB',
    'maxDimensions': 'Dimensioni massime: 2000 x 2000 px',
    'allowedFormats': 'Formati consentiti: PNG, JPG, JPEG',
    'invalidFileType': 'Solo file PNG o JPG/JPEG consentiti',
    'fileTooLarge': 'File troppo grande',
    'imageTooLarge': 'Immagine troppo grande',
    'invalidImage': 'Immagine non valida',
    'imageValidated': '✓ Immagine convalidata con successo',
    'upTo': 'fino a',
    'select': 'Seleziona',
    
    // Messaggi di errore e stato
    'error': 'Errore',
    'success': 'Successo',
    'warning': 'Avviso',
    'info': 'Informazione',
    
    // Placeholder
    'enterTitle': 'Es: Saggio sulla Rivoluzione Industriale',
    'enterDescription': 'Descrivi gli obiettivi e i requisiti del compito...',
    'enterEmail': 'tuo@email.com',
    'enterName': 'Mario Rossi',
    
    // Dialoghi e conferme
    'createTaskDialog': 'Crea un compito, modulo interattivo o carica contenuti multimediali',
    'pleaseEnterTitle': 'Inserisci un titolo',
    
    // Tab e navigazione
    'tasks': 'Compiti',
    'mySubmissions': 'Le Mie Consegne',
    'allSubmissions': 'Tutte le Consegne',
    
    // Pannello Admin
    'totalUsers': 'Utenti Totali',
    'teachers': 'Insegnanti',
    'userManagement': 'Gestione Utenti',
    'manageUsersDescription': 'Visualizza, gestisci e modera tutti gli utenti nel sistema',
    'allUsers': 'Tutti gli Utenti',
    'noUsers': 'Nessun utente trovato',
    'noTeachers': 'Nessun insegnante trovato',
    'noStudents': 'Nessuno studente trovato',
    'confirmDeleteUser': 'Sei sicuro di voler eliminare',
    'userDeleted': 'Utente eliminato con successo',
    'errorDeletingUser': 'Errore nell\'eliminazione dell\'utente',
    'errorLoadingUsers': 'Errore nel caricamento degli utenti',
    'noUsersWarning': '⚠️ Impossibile caricare gli utenti',
    'serverDeploymentIssue': 'Il server Edge Function non è distribuito (Errore 403). Controlla il file ERROR_403_QUICK_FIX.md per risolvere questo problema di infrastruttura.',
    'codeCorrectNote': 'Nota: Il codice è corretto. Devi solo configurare Supabase correttamente.',
    'userBlocked': 'bloccato',
    'userUnblocked': 'sbloccato',
    'errorUpdatingUser': 'Errore nell\'aggiornamento dell\'utente',
    'blocked': 'Bloccato',
    'block': 'Blocca',
    'unblock': 'Sblocca',
    'assignTeacher': 'Assegna Insegnante',
    'assignTeacherTo': 'Assegna Insegnante a',
    'selectTeacherDescription': 'Seleziona un insegnante da assegnare a questo studente',
    'selectTeacher': 'Seleziona un insegnante',
    'teacherAssigned': 'Insegnante assegnato con successo',
    'errorAssigningTeacher': 'Errore nell\'assegnazione dell\'insegnante',
    'adminLoginHint': 'Per admin usa: admin / EduConnect@Admin2024',
    'saving': 'Salvataggio...',
    'of': 'di',
    'selectAll': 'Seleziona Tutti',
    
    // NOTE / Materiale Supplementare
    'notes': 'Materiale',
    'materials': 'Materiale Supplementare',
    'notesDescription': 'Materiale di supporto e risorse educative',
    'createNote': 'Carica Materiale',
    'newMaterial': 'Nuovo Materiale',
    'noteTitle': 'Titolo del Materiale',
    'noteType': 'Tipo di Materiale',
    'book': 'Libro',
    'pdf': 'PDF',
    'photo': 'Foto/Immagine',
    'audio': 'Audio',
    'noNotes': 'Nessun materiale',
    'noNotesMessage': 'Carica il tuo primo materiale educativo per i tuoi studenti',
    'uploadMaterial': 'Carica Materiale',
    'assignNotes': 'Assegna Materiale',
    'statusNew': 'Nuovo',
    'statusUnread': 'Non Letto',
    'statusRead': 'Letto',
    'markAsRead': 'Segna come Letto',
    'deleteNote': 'Elimina Materiale',
    'confirmDeleteNote': 'Sei sicuro di voler eliminare questo materiale?',
    'noteDeleted': 'Materiale eliminato con successo',
    'noteCreated': 'Materiale creato con successo',
    'noteAssigned': 'Materiale assegnato con successo',
    'materialsAssigned': 'materiali assegnati',
    'totalMaterials': 'Totale Materiali',
    'myMaterials': 'Il Mio Materiale',
    
    // Creazione compito con IA
    'createWithAI': 'Crea con IA',
    'aiTaskCreation': 'Creazione Compito con IA',
    'uploadContent': 'Carica Contenuto',
    'contentType': 'Tipo di Contenuto',
    'pasteText': 'Incolla Testo',
    'uploadImage': 'Carica Immagine',
    'videoLink': 'Link Video',
    'uploadPDF': 'Carica PDF',
    'generateTask': 'Genera Compito',
    'aiGenerating': 'IA generando compito...',
    'editGeneratedTask': 'Modifica Compito Generato',
    'generatePDFAndAssign': 'Genera PDF e Assegna',
    'aiAnalyzing': 'IA analizzando contenuto...',
    'aiError': 'Errore generando con IA',
    
    // Organizzazione temporale
    'year': 'Anno',
    'month': 'Mese',
    'week': 'Settimana',
    'january': 'Gennaio',
    'february': 'Febbraio',
    'march': 'Marzo',
    'april': 'Aprile',
    'may': 'Maggio',
    'june': 'Giugno',
    'july': 'Luglio',
    'august': 'Agosto',
    'september': 'Settembre',
    'october': 'Ottobre',
    'november': 'Novembre',
    'december': 'Dicembre',
    'weekOf': 'Settimana del',
    'to': 'al',
    
    // Compiti completati
    'completed': 'Completato',
    'viewSubmission': 'Vedi Consegna',
    'reassigned': 'Riassegnato',
    'attemptHistory': 'Cronologia Tentativi',
    'attempt': 'Tentativo',
    'previousAttempts': 'Tentativi Precedenti',
  },
  
  de: {
    // Navigation und Menü
    'dashboard': 'Dashboard',
    'assignments': 'Aufgaben',
    'grades': 'Noten',
    'students': 'Schüler',
    'submissions': 'Meine Einreichungen',
    'logout': 'Abmelden',
    'myStudents': 'Meine Schüler',
    'allStudents': 'Alle Schüler',
    
    // Authentifizierung
    'login': 'Anmelden',
    'signup': 'Registrieren',
    'email': 'E-Mail',
    'password': 'Passwort',
    'name': 'Name',
    'fullName': 'Vollständiger Name',
    'role': 'Rolle',
    'teacher': 'Lehrer',
    'student': 'Schüler',
    'alreadyHaveAccount': 'Bereits ein Konto?',
    'dontHaveAccount': 'Kein Konto? Verwenden Sie die Registerkarte "Registrieren"',
    'signingIn': 'Anmeldung läuft...',
    'registering': 'Registrierung läuft...',
    'createAccount': 'Konto Erstellen',
    'iAm': 'Ich bin ein...',
    'modernEducationalPlatform': 'Moderne Bildungsplattform',
    'invalidCredentials': 'Ungültige Anmeldeinformationen. Bitte überprüfen Sie Ihre E-Mail und Ihr Passwort oder erstellen Sie ein neues Konto unter "Registrieren".',
    'loginError': 'Anmeldefehler',
    'signupError': 'Registrierungsfehler',
    
    // Dashboard
    'welcome': 'Willkommen',
    'teacherPanel': 'Lehrer-Panel',
    'studentPanel': 'Schüler-Panel',
    'totalAssignments': 'Gesamt Aufgaben',
    'totalStudents': 'Gesamt Schüler',
    'myStudentsCount': 'Meine Schüler',
    'activeAssignments': 'Aktive Aufgaben',
    'pendingSubmissions': 'Ausstehende Einreichungen',
    'recentAssignments': 'Neueste Aufgaben',
    'upcomingAssignments': 'Bevorstehende Aufgaben',
    'completedAssignments': 'Abgeschlossene Aufgaben',
    'averageGrade': 'Durchschnitt',
    'myTasks': 'Meine Aufgaben',
    'manageTasks': 'Verwalten Sie Ihre Aufgaben und Aktivitäten',
    'loadingTasks': 'Aufgaben werden geladen...',
    'loadingSubmissions': 'Einreichungen werden geladen...',
    'noAssignments': 'Keine Aufgaben erstellt',
    'noAssignmentsMessage': 'Beginnen Sie mit der Erstellung Ihrer ersten Aufgabe für Ihre Schüler',
    'createFirstTask': 'Erste Aufgabe Erstellen',
    'noAssignedTasks': 'Keine Aufgaben zugewiesen',
    'noAssignedTasksMessage': 'Ihr Lehrer hat Ihnen noch keine Aufgaben zugewiesen.',
    'noSubmissions': 'Keine Einreichungen',
    'noSubmissionsMessage': 'Sie haben noch keine Aufgaben eingereicht.',
    
    // Aufgaben
    'createAssignment': 'Neue Aufgabe Erstellen',
    'newTask': 'Neue Aufgabe',
    'assignmentTitle': 'Aufgabentitel',
    'description': 'Beschreibung',
    'dueDate': 'Fälligkeitsdatum',
    'submit': 'Einreichen',
    'submitted': 'Eingereicht',
    'pending': 'Ausstehend',
    'graded': 'Benotet',
    'notGraded': 'Nicht Benotet',
    'viewDetails': 'Details Anzeigen',
    'delete': 'Löschen',
    'assignmentDetails': 'Aufgabendetails',
    'submissionDetails': 'Einreichungsdetails',
    'yourAnswer': 'Ihre Antwort',
    'submitAssignment': 'Aufgabe Einreichen',
    'confirmDelete': 'Sind Sie sicher, dass Sie diese Aufgabe löschen möchten?',
    'deleteError': 'Fehler beim Löschen der Aufgabe',
    'createError': 'Fehler beim Erstellen der Aufgabe',
    'grade': 'Note',
    'feedback': 'Rückmeldung',
    'saveGrade': 'Note Speichern',
    'gradeStudent': 'Schüler Benoten',
    'enterGrade': 'Geben Sie eine Note ein (0-100)',
    'enterFeedback': 'Schreiben Sie Ihre Rückmeldung...',
    
    // Aktivitätstypen
    'standard': 'Standard',
    'interactive': 'Interaktiv',
    'form': 'Formular',
    'video': 'Video',
    
    // Interaktive Aktivitäten
    'fillBlanks': 'Lücken Füllen',
    'matchPairs': 'Paare Zuordnen',
    'sequence': 'Reihenfolge',
    'categorize': 'Kategorisieren',
    'trueFalse': 'Wahr/Falsch',
    'imageChoice': 'Bildauswahl',
    'addActivity': 'Aktivität Hinzufügen',
    'activityType': 'Aktivitätstyp',
    'question': 'Frage',
    'correctAnswer': 'Richtige Antwort',
    'addOption': 'Option Hinzufügen',
    'option': 'Option',
    'true': 'Wahr',
    'false': 'Falsch',
    'category': 'Kategorie',
    'addCategory': 'Kategorie Hinzufügen',
    'addItem': 'Element Hinzufügen',
    'item': 'Element',
    'pair': 'Paar',
    'addPair': 'Paar Hinzufügen',
    
    // Formulare
    'addField': 'Feld Hinzufügen',
    'fieldLabel': 'Feldbezeichnung',
    'fieldType': 'Feldtyp',
    'required': 'Erforderlich',
    'text': 'Text',
    'textarea': 'Textbereich',
    'number': 'Nummer',
    'date': 'Datum',
    'checkbox': 'Kontrollkästchen',
    'select': 'Auswählen',
    'radio': 'Radio',
    'options': 'Optionen (durch Komma getrennt)',
    
    // Dateien und Medien
    'attachedFiles': 'Angehängte Dateien (PDFs, Dokumente usw.)',
    'clickToUpload': 'Klicken Sie zum Hochladen von Dateien',
    'uploading': 'Hochladen...',
    'uploadError': 'Fehler beim Hochladen von Dateien',
    'videoUrl': 'Video-URL',
    'videoSupport': 'Unterstützt YouTube, Vimeo und direkte Videodatei-Links',
    'uploadVideo': 'Oder laden Sie ein Video von Ihrem Computer hoch',
    'clickToUploadVideo': 'Klicken Sie zum Hochladen des Videos',
    
    // Schüler und Zuweisungen
    'assignStudents': 'Schüler Zuweisen',
    'assignedStudents': 'Zugewiesene Schüler',
    'availableStudents': 'Verfügbare Schüler',
    'assign': 'Zuweisen',
    'unassign': 'Entfernen',
    'assignToMe': 'Mir Zuweisen',
    'unassignFromMe': 'Von Mir Entfernen',
    'myTeacher': 'Mein Lehrer',
    'noTeacher': 'Kein Lehrer zugewiesen',
    'assignSuccess': 'Erfolgreich zugewiesen',
    'assignError': 'Zuweisungsfehler',
    'assignStudentSuccess': 'Schüler erfolgreich zugewiesen',
    'unassignStudentSuccess': 'Schüler erfolgreich entfernt',
    'assignTaskSuccess': 'Aufgabe erfolgreich zugewiesen',
    'unassignTaskSuccess': 'Aufgabe erfolgreich entfernt',
    'studentsAssigned': 'Schüler zugewiesen',
    'submissions': 'Einreichungen',
    'howAssignmentWorks': '💡 Wie funktioniert das Zuweisungssystem?',
    'assignmentStep1': 'Erstellen Sie eine Aufgabe mit der Schaltfläche "Neue Aufgabe"',
    'assignmentStep2': 'Gehen Sie zu "Alle Schüler" und weisen Sie sich Schüler zu',
    'assignmentStep3': 'Verwenden Sie bei jeder Aufgabe die Benutzerschaltfläche, um sie bestimmten Schülern zuzuweisen',
    'assignmentStep4': 'Schüler sehen nur Aufgaben, die Sie ihnen zugewiesen haben',
    
    // Noten
    'viewGrades': 'Noten Anzeigen',
    'studentGrades': 'Schülernoten',
    'assignmentGrades': 'Noten nach Aufgabe',
    'noGrades': 'Keine Noten verfügbar',
    'noGradesMessage': 'Es gibt noch keine benoteten Einreichungen.',
    'points': 'Punkte',
    
    // Allgemein
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'edit': 'Bearbeiten',
    'close': 'Schließen',
    'loading': 'Laden...',
    'noData': 'Keine Daten verfügbar',
    'search': 'Suchen',
    'filter': 'Filtern',
    'settings': 'Einstellungen',
    'settingsDescription': 'Passen Sie Ihr Profil, Thema und Spracheinstellungen an',
    'profile': 'Profil',
    'language': 'Sprache',
    'theme': 'Thema',
    'lightMode': 'Heller Modus',
    'darkMode': 'Dunkler Modus',
    'selectLanguage': 'Sprache Wählen',
    'changeAvatar': 'Avatar Ändern',
    'selectAvatar': 'Wählen Sie Ihren Avatar',
    'skinTone': 'Hautton',
    'hairColor': 'Haarfarbe',
    'style': 'Stil',
    'customization': 'Anpassung',
    'appearance': 'Aussehen',
    'saveChanges': 'Änderungen Speichern',
    'changesSaved': 'Änderungen erfolgreich gespeichert',
    'errorSavingChanges': 'Fehler beim Speichern der Änderungen',
    'unsavedChanges': 'Nicht gespeicherte Änderungen verwerfen?',
    'saving': 'Speichern...',
    'uploadOwn': 'Eigenes hochladen',
    'uploadRequirements': 'Upload-Anforderungen',
    'maxFileSize': 'Max. Dateigröße: 2 MB',
    'maxDimensions': 'Max. Abmessungen: 2000 x 2000 px',
    'allowedFormats': 'Erlaubte Formate: PNG, JPG, JPEG',
    'invalidFileType': 'Nur PNG oder JPG/JPEG Dateien erlaubt',
    'fileTooLarge': 'Datei zu groß',
    'imageTooLarge': 'Bild zu groß',
    'invalidImage': 'Ungültiges Bild',
    'imageValidated': '✓ Bild erfolgreich validiert',
    'upTo': 'bis zu',
    'select': 'Auswählen',
    
    // Fehler- und Statusmeldungen
    'error': 'Fehler',
    'success': 'Erfolg',
    'warning': 'Warnung',
    'info': 'Information',
    
    // Platzhalter
    'enterTitle': 'Z.B.: Aufsatz über die Industrielle Revolution',
    'enterDescription': 'Beschreiben Sie die Ziele und Anforderungen der Aufgabe...',
    'enterEmail': 'du@email.com',
    'enterName': 'Max Mustermann',
    
    // Dialoge und Bestätigungen
    'createTaskDialog': 'Erstellen Sie eine Aufgabe, ein interaktives Formular oder laden Sie Multimedia-Inhalte hoch',
    'pleaseEnterTitle': 'Bitte geben Sie einen Titel ein',
    
    // Tabs und Navigation
    'tasks': 'Aufgaben',
    'mySubmissions': 'Meine Einreichungen',
    'allSubmissions': 'Alle Einreichungen',
    
    // Admin-Panel
    'totalUsers': 'Gesamte Benutzer',
    'teachers': 'Lehrer',
    'userManagement': 'Benutzerverwaltung',
    'manageUsersDescription': 'Alle Benutzer im System anzeigen, verwalten und moderieren',
    'allUsers': 'Alle Benutzer',
    'noUsers': 'Keine Benutzer gefunden',
    'noTeachers': 'Keine Lehrer gefunden',
    'noStudents': 'Keine Schüler gefunden',
    'confirmDeleteUser': 'Sind Sie sicher, dass Sie löschen möchten',
    'userDeleted': 'Benutzer erfolgreich gelöscht',
    'errorDeletingUser': 'Fehler beim Löschen des Benutzers',
    'errorLoadingUsers': 'Fehler beim Laden der Benutzer',
    'noUsersWarning': '⚠️ Benutzer können nicht geladen werden',
    'serverDeploymentIssue': 'Der Edge Function-Server ist nicht bereitgestellt (Fehler 403). Bitte überprüfen Sie die Datei ERROR_403_QUICK_FIX.md, um dieses Infrastrukturproblem zu lösen.',
    'codeCorrectNote': 'Hinweis: Der Code ist korrekt. Sie müssen nur Supabase richtig konfigurieren.',
    'userBlocked': 'gesperrt',
    'userUnblocked': 'entsperrt',
    'errorUpdatingUser': 'Fehler beim Aktualisieren des Benutzers',
    'blocked': 'Gesperrt',
    'block': 'Sperren',
    'unblock': 'Entsperren',
    'assignTeacher': 'Lehrer zuweisen',
    'assignTeacherTo': 'Lehrer zuweisen an',
    'selectTeacherDescription': 'Wählen Sie einen Lehrer für diesen Schüler',
    'selectTeacher': 'Wählen Sie einen Lehrer',
    'teacherAssigned': 'Lehrer erfolgreich zugewiesen',
    'errorAssigningTeacher': 'Fehler beim Zuweisen des Lehrers',
    'adminLoginHint': 'Für Admin verwenden: admin / EduConnect@Admin2024',
    'saving': 'Speichern...',
    'of': 'von',
    'selectAll': 'Alle auswählen',
    
    // NOTIZEN / Ergänzendes Material
    'notes': 'Material',
    'materials': 'Ergänzendes Material',
    'notesDescription': 'Unterstützungsmaterial und Bildungsressourcen',
    'createNote': 'Material hochladen',
    'newMaterial': 'Neues Material',
    'noteTitle': 'Materialtitel',
    'noteType': 'Materialtyp',
    'book': 'Buch',
    'pdf': 'PDF',
    'photo': 'Foto/Bild',
    'audio': 'Audio',
    'noNotes': 'Kein Material',
    'noNotesMessage': 'Laden Sie Ihr erstes Bildungsmaterial für Ihre Schüler hoch',
    'uploadMaterial': 'Material hochladen',
    'assignNotes': 'Material zuweisen',
    'statusNew': 'Neu',
    'statusUnread': 'Ungelesen',
    'statusRead': 'Gelesen',
    'markAsRead': 'Als gelesen markieren',
    'deleteNote': 'Material löschen',
    'confirmDeleteNote': 'Sind Sie sicher, dass Sie dieses Material löschen möchten?',
    'noteDeleted': 'Material erfolgreich gelöscht',
    'noteCreated': 'Material erfolgreich erstellt',
    'noteAssigned': 'Material erfolgreich zugewiesen',
    'materialsAssigned': 'Materialien zugewiesen',
    'totalMaterials': 'Gesamt Material',
    'myMaterials': 'Mein Material',
    
    // KI-Aufgabenerstellung
    'createWithAI': 'Mit KI erstellen',
    'aiTaskCreation': 'KI-Aufgabenerstellung',
    'uploadContent': 'Inhalt hochladen',
    'contentType': 'Inhaltstyp',
    'pasteText': 'Text einfügen',
    'uploadImage': 'Bild hochladen',
    'videoLink': 'Videolink',
    'uploadPDF': 'PDF hochladen',
    'generateTask': 'Aufgabe generieren',
    'aiGenerating': 'KI generiert Aufgabe...',
    'editGeneratedTask': 'Generierte Aufgabe bearbeiten',
    'generatePDFAndAssign': 'PDF generieren und zuweisen',
    'aiAnalyzing': 'KI analysiert Inhalt...',
    'aiError': 'Fehler beim Generieren mit KI',
    
    // Zeitliche Organisation
    'year': 'Jahr',
    'month': 'Monat',
    'week': 'Woche',
    'january': 'Januar',
    'february': 'Februar',
    'march': 'März',
    'april': 'April',
    'may': 'Mai',
    'june': 'Juni',
    'july': 'Juli',
    'august': 'August',
    'september': 'September',
    'october': 'Oktober',
    'november': 'November',
    'december': 'Dezember',
    'weekOf': 'Woche vom',
    'to': 'bis',
    
    // Abgeschlossene Aufgaben
    'completed': 'Abgeschlossen',
    'viewSubmission': 'Einreichung ansehen',
    'reassigned': 'Neu zugewiesen',
    'attemptHistory': 'Versuchshistorie',
    'attempt': 'Versuch',
    'previousAttempts': 'Frühere Versuche',
  },
  
  fr: {
    // Navigation et menu
    'dashboard': 'Tableau de Bord',
    'assignments': 'Devoirs',
    'grades': 'Notes',
    'students': 'Étudiants',
    'submissions': 'Mes Soumissions',
    'logout': 'Déconnexion',
    'myStudents': 'Mes Étudiants',
    'allStudents': 'Tous les Étudiants',
    
    // Authentification
    'login': 'Connexion',
    'signup': "S'inscrire",
    'email': 'Email',
    'password': 'Mot de Passe',
    'name': 'Nom',
    'fullName': 'Nom Complet',
    'role': 'Rôle',
    'teacher': 'Professeur',
    'student': 'Étudiant',
    'alreadyHaveAccount': 'Vous avez déjà un compte?',
    'dontHaveAccount': 'Pas de compte? Utilisez l\'onglet "S\'inscrire"',
    'signingIn': 'Connexion en cours...',
    'registering': 'Inscription en cours...',
    'createAccount': 'Créer un Compte',
    'iAm': 'Je suis un...',
    'modernEducationalPlatform': 'Plateforme éducative moderne',
    'invalidCredentials': 'Identifiants invalides. Veuillez vérifier votre email et mot de passe, ou créer un nouveau compte dans "S\'inscrire".',
    'loginError': 'Erreur de connexion',
    'signupError': 'Erreur d\'inscription',
    
    // Tableau de bord
    'welcome': 'Bienvenue',
    'teacherPanel': 'Panneau Professeur',
    'studentPanel': 'Panneau Étudiant',
    'totalAssignments': 'Total des Devoirs',
    'totalStudents': 'Total des Étudiants',
    'myStudentsCount': 'Mes Étudiants',
    'activeAssignments': 'Devoirs Actifs',
    'pendingSubmissions': 'Soumissions en Attente',
    'recentAssignments': 'Devoirs Récents',
    'upcomingAssignments': 'Devoirs à Venir',
    'completedAssignments': 'Devoirs Terminés',
    'averageGrade': 'Moyenne',
    'myTasks': 'Mes Tâches',
    'manageTasks': 'Gérez vos tâches et activités',
    'loadingTasks': 'Chargement des tâches...',
    'loadingSubmissions': 'Chargement des soumissions...',
    'noAssignments': 'Aucun devoir créé',
    'noAssignmentsMessage': 'Commencez par créer votre premier devoir pour vos étudiants',
    'createFirstTask': 'Créer la Première Tâche',
    'noAssignedTasks': 'Aucun devoir assigné',
    'noAssignedTasksMessage': 'Votre professeur ne vous a encore assigné aucune tâche.',
    'noSubmissions': 'Aucune soumission',
    'noSubmissionsMessage': "Vous n'avez encore soumis aucun devoir.",
    
    // Devoirs
    'createAssignment': 'Créer un Nouveau Devoir',
    'newTask': 'Nouvelle Tâche',
    'assignmentTitle': 'Titre du Devoir',
    'description': 'Description',
    'dueDate': 'Date Limite',
    'submit': 'Soumettre',
    'submitted': 'Soumis',
    'pending': 'En Attente',
    'graded': 'Noté',
    'notGraded': 'Non Noté',
    'viewDetails': 'Voir les Détails',
    'delete': 'Supprimer',
    'assignmentDetails': 'Détails du Devoir',
    'submissionDetails': 'Détails de la Soumission',
    'yourAnswer': 'Votre réponse',
    'submitAssignment': 'Soumettre le Devoir',
    'confirmDelete': 'Êtes-vous sûr de vouloir supprimer ce devoir?',
    'deleteError': 'Erreur lors de la suppression du devoir',
    'createError': 'Erreur lors de la création du devoir',
    'grade': 'Note',
    'feedback': 'Commentaires',
    'saveGrade': 'Enregistrer la Note',
    'gradeStudent': 'Noter l\'Étudiant',
    'enterGrade': 'Entrez une note (0-100)',
    'enterFeedback': 'Écrivez vos commentaires...',
    
    // Types d'activités
    'standard': 'Standard',
    'interactive': 'Interactif',
    'form': 'Formulaire',
    'video': 'Vidéo',
    
    // Activités interactives
    'fillBlanks': 'Remplir les Blancs',
    'matchPairs': 'Associer les Paires',
    'sequence': 'Séquence',
    'categorize': 'Catégoriser',
    'trueFalse': 'Vrai/Faux',
    'imageChoice': 'Choix d\'Image',
    'addActivity': 'Ajouter une Activité',
    'activityType': 'Type d\'Activité',
    'question': 'Question',
    'correctAnswer': 'Réponse Correcte',
    'addOption': 'Ajouter une Option',
    'option': 'Option',
    'true': 'Vrai',
    'false': 'Faux',
    'category': 'Catégorie',
    'addCategory': 'Ajouter une Catégorie',
    'addItem': 'Ajouter un Élément',
    'item': 'Élément',
    'pair': 'Paire',
    'addPair': 'Ajouter une Paire',
    
    // Formulaires
    'addField': 'Ajouter un Champ',
    'fieldLabel': 'Étiquette du Champ',
    'fieldType': 'Type de Champ',
    'required': 'Obligatoire',
    'text': 'Texte',
    'textarea': 'Zone de Texte',
    'number': 'Nombre',
    'date': 'Date',
    'checkbox': 'Case à Cocher',
    'select': 'Sélectionner',
    'radio': 'Radio',
    'options': 'Options (séparées par des virgules)',
    
    // Fichiers et médias
    'attachedFiles': 'Fichiers Joints (PDFs, documents, etc.)',
    'clickToUpload': 'Cliquez pour télécharger des fichiers',
    'uploading': 'Téléchargement...',
    'uploadError': 'Erreur lors du téléchargement des fichiers',
    'videoUrl': 'URL de la Vidéo',
    'videoSupport': 'Prend en charge YouTube, Vimeo et les liens directs vers des fichiers vidéo',
    'uploadVideo': 'Ou téléchargez une vidéo depuis votre ordinateur',
    'clickToUploadVideo': 'Cliquez pour télécharger la vidéo',
    
    // Étudiants et affectations
    'assignStudents': 'Assigner des Étudiants',
    'assignedStudents': 'Étudiants Assignés',
    'availableStudents': 'Étudiants Disponibles',
    'assign': 'Assigner',
    'unassign': 'Désassigner',
    'assignToMe': 'M\'Assigner',
    'unassignFromMe': 'Me Désassigner',
    'myTeacher': 'Mon Professeur',
    'noTeacher': 'Aucun professeur assigné',
    'assignSuccess': 'Assignation réussie',
    'assignError': 'Erreur d\'assignation',
    'assignStudentSuccess': 'Étudiant assigné avec succès',
    'unassignStudentSuccess': 'Étudiant désassigné avec succès',
    'assignTaskSuccess': 'Tâche assignée avec succès',
    'unassignTaskSuccess': 'Tâche désassignée avec succès',
    'studentsAssigned': 'étudiants assignés',
    'submissions': 'soumissions',
    'howAssignmentWorks': '💡 Comment fonctionne le système d\'assignation?',
    'assignmentStep1': 'Créez une tâche en utilisant le bouton "Nouvelle Tâche"',
    'assignmentStep2': 'Allez dans "Tous les Étudiants" et assignez-vous des étudiants',
    'assignmentStep3': 'Depuis chaque tâche, utilisez le bouton utilisateurs pour l\'assigner à des étudiants spécifiques',
    'assignmentStep4': 'Les étudiants ne verront que les tâches que vous leur avez assignées',
    
    // Notes
    'viewGrades': 'Voir les Notes',
    'studentGrades': 'Notes des Étudiants',
    'assignmentGrades': 'Notes par Devoir',
    'noGrades': 'Aucune note disponible',
    'noGradesMessage': 'Il n\'y a pas encore de soumissions notées.',
    'points': 'points',
    
    // Général
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'edit': 'Modifier',
    'close': 'Fermer',
    'loading': 'Chargement...',
    'noData': 'Aucune donnée disponible',
    'search': 'Rechercher',
    'filter': 'Filtrer',
    'settings': 'Paramètres',
    'settingsDescription': 'Personnalisez votre profil, thème et préférences de langue',
    'profile': 'Profil',
    'language': 'Langue',
    'theme': 'Thème',
    'lightMode': 'Mode Clair',
    'darkMode': 'Mode Sombre',
    'selectLanguage': 'Sélectionner la Langue',
    'changeAvatar': 'Changer l\'Avatar',
    'selectAvatar': 'Sélectionnez Votre Avatar',
    'skinTone': 'Teint de Peau',
    'hairColor': 'Couleur de Cheveux',
    'style': 'Style',
    'customization': 'Personnalisation',
    'appearance': 'Apparence',
    'saveChanges': 'Enregistrer les Modifications',
    'changesSaved': 'Modifications enregistrées avec succès',
    'errorSavingChanges': 'Erreur lors de l\'enregistrement des modifications',
    'unsavedChanges': 'Abandonner les modifications non enregistrées?',
    'uploadOwn': 'Télécharger la vôtre',
    'uploadRequirements': 'Exigences de téléchargement',
    'maxFileSize': 'Taille max: 2 MB',
    'maxDimensions': 'Dimensions max: 2000 x 2000 px',
    'allowedFormats': 'Formats autorisés: PNG, JPG, JPEG',
    'invalidFileType': 'Seuls les fichiers PNG ou JPG/JPEG sont autorisés',
    'fileTooLarge': 'Fichier trop volumineux',
    'imageTooLarge': 'Image trop grande',
    'invalidImage': 'Image invalide',
    'imageValidated': '✓ Image validée avec succès',
    'upTo': 'jusqu\'à',
    'select': 'Sélectionner',
    
    // Messages d'erreur et de statut
    'error': 'Erreur',
    'success': 'Succès',
    'warning': 'Avertissement',
    'info': 'Information',
    
    // Espaces réservés
    'enterTitle': 'Ex: Essai sur la Révolution Industrielle',
    'enterDescription': 'Décrivez les objectifs et les exigences de la tâche...',
    'enterEmail': 'vous@email.com',
    'enterName': 'Jean Dupont',
    
    // Dialogues et confirmations
    'createTaskDialog': 'Créez une tâche, un formulaire interactif ou téléchargez du contenu multimédia',
    'pleaseEnterTitle': 'Veuillez entrer un titre',
    
    // Onglets et navigation
    'tasks': 'Tâches',
    'mySubmissions': 'Mes Soumissions',
    'allSubmissions': 'Toutes les Soumissions',
    
    // Panneau Admin
    'totalUsers': 'Utilisateurs Totaux',
    'teachers': 'Enseignants',
    'userManagement': 'Gestion des Utilisateurs',
    'manageUsersDescription': 'Afficher, gérer et modérer tous les utilisateurs du système',
    'allUsers': 'Tous les Utilisateurs',
    'noUsers': 'Aucun utilisateur trouvé',
    'noTeachers': 'Aucun enseignant trouvé',
    'noStudents': 'Aucun étudiant trouvé',
    'confirmDeleteUser': 'Êtes-vous sûr de vouloir supprimer',
    'userDeleted': 'Utilisateur supprimé avec succès',
    'errorDeletingUser': 'Erreur lors de la suppression de l\'utilisateur',
    'errorLoadingUsers': 'Erreur lors du chargement des utilisateurs',
    'noUsersWarning': '⚠️ Impossible de charger les utilisateurs',
    'serverDeploymentIssue': 'Le serveur Edge Function n\'est pas déployé (Erreur 403). Veuillez consulter le fichier ERROR_403_QUICK_FIX.md pour résoudre ce problème d\'infrastructure.',
    'codeCorrectNote': 'Note: Le code est correct. Vous devez simplement configurer Supabase correctement.',
    'userBlocked': 'bloqué',
    'userUnblocked': 'débloqué',
    'errorUpdatingUser': 'Erreur lors de la mise à jour de l\'utilisateur',
    'blocked': 'Bloqué',
    'block': 'Bloquer',
    'unblock': 'Débloquer',
    'assignTeacher': 'Assigner un Enseignant',
    'assignTeacherTo': 'Assigner un Enseignant à',
    'selectTeacherDescription': 'Sélectionnez un enseignant à assigner à cet étudiant',
    'selectTeacher': 'Sélectionnez un enseignant',
    'teacherAssigned': 'Enseignant assigné avec succès',
    'errorAssigningTeacher': 'Erreur lors de l\'assignation de l\'enseignant',
    'adminLoginHint': 'Pour admin utilisez: admin / EduConnect@Admin2024',
    'saving': 'Enregistrement...',
    'of': 'de',
    'selectAll': 'Tout sélectionner',
    
    // NOTES / Matériel Supplémentaire
    'notes': 'Matériel',
    'materials': 'Matériel Supplémentaire',
    'notesDescription': 'Matériel de soutien et ressources éducatives',
    'createNote': 'Télécharger Matériel',
    'newMaterial': 'Nouveau Matériel',
    'noteTitle': 'Titre du Matériel',
    'noteType': 'Type de Matériel',
    'book': 'Livre',
    'pdf': 'PDF',
    'photo': 'Photo/Image',
    'audio': 'Audio',
    'noNotes': 'Aucun matériel',
    'noNotesMessage': 'Téléchargez votre premier matériel éducatif pour vos étudiants',
    'uploadMaterial': 'Télécharger Matériel',
    'assignNotes': 'Assigner Matériel',
    'statusNew': 'Nouveau',
    'statusUnread': 'Non Lu',
    'statusRead': 'Lu',
    'markAsRead': 'Marquer comme Lu',
    'deleteNote': 'Supprimer Matériel',
    'confirmDeleteNote': 'Êtes-vous sûr de vouloir supprimer ce matériel?',
    'noteDeleted': 'Matériel supprimé avec succès',
    'noteCreated': 'Matériel créé avec succès',
    'noteAssigned': 'Matériel assigné avec succès',
    'materialsAssigned': 'matériels assignés',
    'totalMaterials': 'Total Matériels',
    'myMaterials': 'Mon Matériel',
    
    // Création de tâche avec IA
    'createWithAI': 'Créer avec IA',
    'aiTaskCreation': 'Création de Tâche avec IA',
    'uploadContent': 'Télécharger Contenu',
    'contentType': 'Type de Contenu',
    'pasteText': 'Coller Texte',
    'uploadImage': 'Télécharger Image',
    'videoLink': 'Lien Vidéo',
    'uploadPDF': 'Télécharger PDF',
    'generateTask': 'Générer Tâche',
    'aiGenerating': 'IA générant tâche...',
    'editGeneratedTask': 'Modifier Tâche Générée',
    'generatePDFAndAssign': 'Générer PDF et Assigner',
    'aiAnalyzing': 'IA analysant contenu...',
    'aiError': 'Erreur lors de la génération avec IA',
    
    // Organisation temporelle
    'year': 'Année',
    'month': 'Mois',
    'week': 'Semaine',
    'january': 'Janvier',
    'february': 'Février',
    'march': 'Mars',
    'april': 'Avril',
    'may': 'Mai',
    'june': 'Juin',
    'july': 'Juillet',
    'august': 'Août',
    'september': 'Septembre',
    'october': 'Octobre',
    'november': 'Novembre',
    'december': 'Décembre',
    'weekOf': 'Semaine du',
    'to': 'au',
    
    // Tâches terminées
    'completed': 'Terminé',
    'viewSubmission': 'Voir Soumission',
    'reassigned': 'Réassigné',
    'attemptHistory': 'Historique des Tentatives',
    'attempt': 'Tentative',
    'previousAttempts': 'Tentatives Précédentes',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('educonnect-language');
    return (saved as Language) || 'es';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('educonnect-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['es'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t,
      currentLanguage: language,
      changeLanguage: setLanguage
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

export const languageNames: Record<Language, string> = {
  es: 'Español',
  en: 'English',
  it: 'Italiano',
  de: 'Deutsch',
  fr: 'Français',
};
